//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Lab2Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Lab2Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Lab2Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Lab2Controls"",
    ""maps"": [
        {
            ""name"": ""Controls"",
            ""id"": ""e049e5f5-8594-4899-8d40-551f1a9a7603"",
            ""actions"": [
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""b9eb0040-f106-47d2-bcc0-b4544fb37502"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cameras"",
                    ""type"": ""Button"",
                    ""id"": ""c9825ffc-8e61-4250-a36e-6984ca8a5f1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3c2d4f2a-7f8c-4008-8688-4b0ef5754469"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6e1c360-c5c6-44a2-aa60-6b87bb892260"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cameras"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Controls
        m_Controls = asset.FindActionMap("Controls", throwIfNotFound: true);
        m_Controls_Quit = m_Controls.FindAction("Quit", throwIfNotFound: true);
        m_Controls_Cameras = m_Controls.FindAction("Cameras", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Controls
    private readonly InputActionMap m_Controls;
    private IControlsActions m_ControlsActionsCallbackInterface;
    private readonly InputAction m_Controls_Quit;
    private readonly InputAction m_Controls_Cameras;
    public struct ControlsActions
    {
        private @Lab2Controls m_Wrapper;
        public ControlsActions(@Lab2Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Quit => m_Wrapper.m_Controls_Quit;
        public InputAction @Cameras => m_Wrapper.m_Controls_Cameras;
        public InputActionMap Get() { return m_Wrapper.m_Controls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlsActions set) { return set.Get(); }
        public void SetCallbacks(IControlsActions instance)
        {
            if (m_Wrapper.m_ControlsActionsCallbackInterface != null)
            {
                @Quit.started -= m_Wrapper.m_ControlsActionsCallbackInterface.OnQuit;
                @Quit.performed -= m_Wrapper.m_ControlsActionsCallbackInterface.OnQuit;
                @Quit.canceled -= m_Wrapper.m_ControlsActionsCallbackInterface.OnQuit;
                @Cameras.started -= m_Wrapper.m_ControlsActionsCallbackInterface.OnCameras;
                @Cameras.performed -= m_Wrapper.m_ControlsActionsCallbackInterface.OnCameras;
                @Cameras.canceled -= m_Wrapper.m_ControlsActionsCallbackInterface.OnCameras;
            }
            m_Wrapper.m_ControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Quit.started += instance.OnQuit;
                @Quit.performed += instance.OnQuit;
                @Quit.canceled += instance.OnQuit;
                @Cameras.started += instance.OnCameras;
                @Cameras.performed += instance.OnCameras;
                @Cameras.canceled += instance.OnCameras;
            }
        }
    }
    public ControlsActions @Controls => new ControlsActions(this);
    public interface IControlsActions
    {
        void OnQuit(InputAction.CallbackContext context);
        void OnCameras(InputAction.CallbackContext context);
    }
}
